version: '3.4'

services:
  sagademo:
    image: sagademo
    build:
      context: .
      dockerfile: SagaDemo/Dockerfile
    depends_on: 
     - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment: 
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
